### ISSUE TITLE
MissingPluginException(No implementation found for method createPreSignedURL on channel aws_s3_plugin_flutter)

### ISSUE THREAD

**Issue by IamAKX** [mdavidkhan/aws_s3_plugin_flutter#1]
Getting following error at line   **String presigned = await awsS3.getPreSignedURLOfFile;**

_presigned URL failed with error MissingPluginException(No implementation found for method createPreSignedURL on channel aws_s3_plugin_flutter)_

**Comment by mdavidkhan** [comment]
OK brother, I will investigate this issue and will let you know ASAP

**Comment by mdavidkhan** [comment]
Please check now the issue is fixed at android end in version 0.0.4

**Comment by mdavidkhan** [comment]
This issue has been fixed for iOS as well, and this fix is completely available on 0.0.5 version
